stages: 
  # - testDeploy
  - loginDocker
  - build_image
  - deploy_image


before_script:
  # 测试docker是否正常启动
  - whoami
  - docker info

loginDocker:

  stage: loginDocker
  script:
    - docker login -u="catone" -p="u6xrMcM4"

# test:
#   stage: testDeploy
#   script:
#     - 


build:
  stage: build_image
  script:
    # 重新构建docker_image
    - docker build -t="catone/freeFile:test" .

pre_deploy:
  # push到hub.docker 远端用于部署
  stage: deploy_image
  script: 
    - docker push catone/freeFile:test
  when:
    on_success
  only:
    - dev


