stages: 
  # - testDeploy
  - loginDocker
  - pre_build
  - deployTest
  - test
  - cleanTest
  - build_image
  - deploy_image


before_script:
  # 测试docker是否正常启动
  - whoami
  - docker info

loginDocker:

  stage: loginDocker
  script:
    - docker login -u="catone" -p="u6xrMcM4"
  retry: 2

pre_build:
  stage: pre_build
  script:
    # 重新构建docker_image
    - docker build -t="catone/freefile:pre_build" -f ./server/Dockerfile ./server/
  when: always


redisTest:
  stage: deployTest
  script:
    - docker run -d --name="redis_test" redis:latest
  when: always

mysqlTest:
  stage: deployTest
  script:
    - docker run -d --name="mysql_test" mysql:latest
  when: always

freeFileServerEnd:
  stage: deployTest
  script:
    - docker run -d -P --name="free_file_test" catone/freefile:test
  when: always

pyTest:
  stage: test
  script:
    - echo pyTest
  when: always

cleaner:
  stage: cleanTest
  script:
    - echo cleanTestEnv
    - docker rm -f free_file_test 
    - docker rm -f mysql_test
    - docker rm -f redis_test
  when: always

build:
  stage: build_image
  script:
    # 重新构建docker_image
    - docker build -t="catone/freefile:test" -f ./server/Dockerfile ./server/
  dependencies:
    - pyTest  
  when: always

pre_deploy:
  # push到hub.docker 远端用于部署
  stage: deploy_image
  script: 
    - docker push catone/freefile:test
  dependencies:
    - loginDocker
  when: on_success
  only:
    - dev

