stages: 
  # - testDeploy
  - loginDocker
  - test
  - build_image
  - deploy_image


before_script:
  # 测试docker是否正常启动
  - whoami
  - docker info

loginDocker:

  stage: loginDocker
  script:
    - docker login -u="catone" -p="u6xrMcM4"

test1:
  stage: test
  script:
    - echo hello world

test2:
  stage: test
  script:
    - echo hello world

test3:
  stage: test
  script:
    - echo hello world


# test:
#   stage: testDeploy
#   script:
#     - 


build:
  stage: build_image
  script:
    # 重新构建docker_image
    - docker build -t="catone/freefile:test" .
  when:
    always

pre_deploy:
  # push到hub.docker 远端用于部署
  stage: deploy_image
  script: 
    - docker push catone/freefile:test
  when:
    on_success
  only:
    - dev


